import { JsonOutputParser } from "@langchain/core/output_parsers";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { z } from "zod";
import { getModel, hasActiveProviderKey } from "@/lib/ai/model";
import type { SpecPlan } from "@/lib/ai/chains/spec-decompose";

const scaffoldSchema = z.record(z.string(), z.string());
export type ScaffoldFiles = z.infer<typeof scaffoldSchema>;

function buildDeterministicScaffold(plan: SpecPlan): ScaffoldFiles {
  if (plan.prBody.toLowerCase().includes("shipbrain-codegen: handoff-only")) {
    return {
      "SHIPBRAIN_HANDOFF.md": [
        "# ShipBrain Developer Handoff",
        "",
        "ShipBrain intentionally did not modify application source files for this Draft PR.",
        "",
        "The developer should continue work on this feature branch and commit the requested implementation manually.",
        "",
        "## Requested tasks",
        ...plan.tasks.flatMap((task) => [
          "",
          `### ${task.title}`,
          task.description,
          "",
          `Suggested files: ${task.files.join(", ")}`
        ]),
        ""
      ].join("\n")
    };
  }

  const entries = plan.tasks.flatMap((task, taskIndex) =>
    task.files.map((file, fileIndex) => {
      const exportName = `shipbrainTask${taskIndex + 1}_${fileIndex + 1}`.replace(/[^a-zA-Z0-9_]/g, "");
      const content = [
        "/*",
        " * Generated by ShipBrain as a safe first-pass scaffold.",
        " * Replace placeholders with repo-specific implementation details before merging.",
        " */",
        "",
        `export const ${exportName} = ${JSON.stringify(
          {
            title: task.title,
            description: task.description,
            acceptance: "Wire this scaffold into the connected repository following existing project patterns."
          },
          null,
          2
        )};`,
        ""
      ].join("\n");

      return [file, content] as const;
    })
  );

  return Object.fromEntries(entries);
}

export async function generateScaffold(plan: SpecPlan): Promise<ScaffoldFiles> {
  if (plan.prBody.toLowerCase().includes("shipbrain-codegen: handoff-only")) {
    return buildDeterministicScaffold(plan);
  }

  if (!hasActiveProviderKey()) {
    return buildDeterministicScaffold(plan);
  }

  const parser = new JsonOutputParser<ScaffoldFiles>();
  const prompt = ChatPromptTemplate.fromMessages([
    ["system", "Return strict JSON where each key is a filename and each value is concise scaffold code. No markdown."],
    ["human", "Plan:\n{plan}"]
  ]);
  const chain = prompt.pipe(getModel({ temperature: 0.2 })).pipe(parser);
  try {
    return scaffoldSchema.parse(await chain.invoke({ plan: JSON.stringify(plan).replace(/{/g, "{{").replace(/}/g, "}}") }));
  } catch {
    return buildDeterministicScaffold(plan);
  }
}
